import asyncio
import os
import sys
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# Make the app package importable when Alembic runs from this directory.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(Path(__file__).resolve().parents[1] / ".env")

config = context.config


def _async_url(url: str) -> str:
    """Force the asyncpg driver regardless of how CONTINUUM_DATABASE_URL is written.

    core-mcp connects directly via asyncpg (no SQLAlchemy at runtime); SQLAlchemy's
    async engine, which Alembic needs, requires the ``postgresql+asyncpg://`` scheme.
    We normalise here so .env doesn't have to change.
    """
    if url.startswith("postgresql+asyncpg://"):
        return url
    if url.startswith("postgresql://"):
        return "postgresql+asyncpg://" + url[len("postgresql://") :]
    if url.startswith("postgres://"):
        return "postgresql+asyncpg://" + url[len("postgres://") :]
    return url


# Connection URL comes from the app's CONTINUUM_DATABASE_URL, not from alembic.ini —
# keeps a single source of truth.
config.set_main_option("sqlalchemy.url", _async_url(os.environ["CONTINUUM_DATABASE_URL"]))

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# core-mcp has no ORM layer — pgvector types (vector(384), hnsw indexes) have no
# native SQLAlchemy Core representation, so migrations are hand-written with raw
# op.execute(...) SQL rather than autogenerated from model metadata.
target_metadata = None


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table="alembic_version_core",
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        version_table="alembic_version_core",
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
