"""baseline memory fact requests

Revision ID: b407737f3cb3
Revises:
Create Date: 2026-07-17 18:10:56.106937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b407737f3cb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBEDDING_DIM = 384


def upgrade() -> None:
    """Baseline schema, matching the previously hand-rolled DDL in app/infra/pg.py
    exactly so this is a no-op against the already-live continuum_core database.

    pgvector types (vector(N), hnsw indexes) have no native SQLAlchemy Core
    representation, so this is hand-written raw SQL rather than autogenerated.
    """
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS memory (
            owner       TEXT        NOT NULL DEFAULT '',
            name        TEXT        NOT NULL,
            type        TEXT        NOT NULL,
            description TEXT        NOT NULL,
            content     TEXT        NOT NULL,
            embedding   vector({EMBEDDING_DIM}),
            created_at  TIMESTAMPTZ NOT NULL,
            updated_at  TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (owner, name)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS memory_embedding_hnsw_idx ON memory "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS fact (
            id             BIGSERIAL   PRIMARY KEY,
            owner          TEXT        NOT NULL,
            source_name    TEXT        NOT NULL,
            content        TEXT        NOT NULL,
            embedding      vector({EMBEDDING_DIM}) NOT NULL,
            valid_from     TIMESTAMPTZ NOT NULL,
            invalidated_at TIMESTAMPTZ,
            superseded_by  BIGINT      REFERENCES fact(id),
            created_at     TIMESTAMPTZ NOT NULL,
            FOREIGN KEY (owner, source_name) REFERENCES memory(owner, name) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS fact_embedding_hnsw_idx ON fact "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS fact_owner_source_idx ON fact (owner, source_name)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS fact_owner_current_idx ON fact (owner) "
        "WHERE invalidated_at IS NULL"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS requests (
            id          BIGSERIAL PRIMARY KEY,
            timestamp   TIMESTAMPTZ       NOT NULL,
            tool        TEXT              NOT NULL,
            arguments   TEXT,
            status      TEXT              NOT NULL,
            response    TEXT,
            error       TEXT,
            duration_ms DOUBLE PRECISION
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TABLE IF EXISTS requests")
    op.execute("DROP INDEX IF EXISTS fact_owner_current_idx")
    op.execute("DROP INDEX IF EXISTS fact_owner_source_idx")
    op.execute("DROP INDEX IF EXISTS fact_embedding_hnsw_idx")
    op.execute("DROP TABLE IF EXISTS fact")
    op.execute("DROP INDEX IF EXISTS memory_embedding_hnsw_idx")
    op.execute("DROP TABLE IF EXISTS memory")
    # Deliberately not dropping the vector extension on downgrade — other
    # objects/databases on the same Postgres instance may depend on it.
